// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const adjustAccountBalance = `-- name: AdjustAccountBalance :exec
UPDATE accounts
SET current_balance = current_balance + $1,
    updated_at = NOW()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
`

type AdjustAccountBalanceParams struct {
	Delta  decimal.Decimal `json:"delta"`
	ID     uuid.UUID       `json:"id"`
	UserID uuid.UUID       `json:"user_id"`
}

func (q *Queries) AdjustAccountBalance(ctx context.Context, arg AdjustAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, adjustAccountBalance, arg.Delta, arg.ID, arg.UserID)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id, name, account_type, currency,
    initial_balance, current_balance, icon, color, display_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $5, -- current starts equal to initial
    $6,
    $7,
    $8
)
RETURNING id, user_id, name, account_type, currency, initial_balance, current_balance, icon, color, is_archived, display_order, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	Name           string          `json:"name"`
	AccountType    string          `json:"account_type"`
	Currency       string          `json:"currency"`
	InitialBalance decimal.Decimal `json:"initial_balance"`
	Icon           *string         `json:"icon"`
	Color          *string         `json:"color"`
	DisplayOrder   int32           `json:"display_order"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.AccountType,
		arg.Currency,
		arg.InitialBalance,
		arg.Icon,
		arg.Color,
		arg.DisplayOrder,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Icon,
		&i.Color,
		&i.IsArchived,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, account_type, currency, initial_balance, current_balance, icon, color, is_archived, display_order, created_at, updated_at, deleted_at FROM accounts
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Icon,
		&i.Color,
		&i.IsArchived,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, name, account_type, currency, initial_balance, current_balance, icon, color, is_archived, display_order, created_at, updated_at, deleted_at FROM accounts
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY display_order, created_at
`

func (q *Queries) ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountType,
			&i.Currency,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.Icon,
			&i.Color,
			&i.IsArchived,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :one
UPDATE accounts
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteAccount, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1,
    account_type = $2,
    icon = $3,
    color = $4,
    display_order = $5,
    is_archived = $6,
    current_balance = current_balance
        + (COALESCE($7, initial_balance) - initial_balance),
    initial_balance = COALESCE($7, initial_balance),
    updated_at = NOW()
WHERE id = $8 AND user_id = $9 AND deleted_at IS NULL
RETURNING id, user_id, name, account_type, currency, initial_balance, current_balance, icon, color, is_archived, display_order, created_at, updated_at, deleted_at
`

type UpdateAccountParams struct {
	Name           string              `json:"name"`
	AccountType    string              `json:"account_type"`
	Icon           *string             `json:"icon"`
	Color          *string             `json:"color"`
	DisplayOrder   int32               `json:"display_order"`
	IsArchived     bool                `json:"is_archived"`
	InitialBalance decimal.NullDecimal `json:"initial_balance"`
	ID             uuid.UUID           `json:"id"`
	UserID         uuid.UUID           `json:"user_id"`
}

// initial_balance is optional: NULL leaves the opening balance untouched.
// When supplied, current_balance is shifted by the same delta so the invariant
// current_balance = initial_balance + movements keeps holding. Callers must
// only supply it for accounts with no transactions (see AccountService.Update).
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.AccountType,
		arg.Icon,
		arg.Color,
		arg.DisplayOrder,
		arg.IsArchived,
		arg.InitialBalance,
		arg.ID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Currency,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.Icon,
		&i.Color,
		&i.IsArchived,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
