// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    user_id, parent_id, name, category_type, icon, color, display_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	UserID       uuid.NullUUID `json:"user_id"`
	ParentID     uuid.NullUUID `json:"parent_id"`
	Name         string        `json:"name"`
	CategoryType string        `json:"category_type"`
	Icon         *string       `json:"icon"`
	Color        *string       `json:"color"`
	DisplayOrder int32         `json:"display_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.CategoryType,
		arg.Icon,
		arg.Color,
		arg.DisplayOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.CategoryType,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryForUser = `-- name: GetCategoryForUser :one
SELECT id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at FROM categories
WHERE id = $1
  AND deleted_at IS NULL
  AND (user_id = $2 OR is_system = TRUE)
`

type GetCategoryForUserParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"user_id"`
}

// A category is usable if it belongs to the user or is a system category.
func (q *Queries) GetCategoryForUser(ctx context.Context, arg GetCategoryForUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryForUser, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.CategoryType,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOwnedCategory = `-- name: GetOwnedCategory :one
SELECT id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at FROM categories
WHERE id = $1 AND user_id = $2 AND is_system = FALSE AND deleted_at IS NULL
`

type GetOwnedCategoryParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"user_id"`
}

// Only the user's own (non-system) category; used for update/delete.
func (q *Queries) GetOwnedCategory(ctx context.Context, arg GetOwnedCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getOwnedCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.CategoryType,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategoriesForUser = `-- name: ListCategoriesForUser :many
SELECT id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at FROM categories
WHERE deleted_at IS NULL AND (user_id = $1 OR is_system = TRUE)
ORDER BY is_system DESC, category_type, display_order, name
`

// System categories plus the user's own, usable for selection.
func (q *Queries) ListCategoriesForUser(ctx context.Context, userID uuid.NullUUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.CategoryType,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemCategories = `-- name: ListSystemCategories :many
SELECT id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at FROM categories
WHERE is_system = TRUE AND deleted_at IS NULL
ORDER BY category_type, display_order, name
`

func (q *Queries) ListSystemCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSystemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.CategoryType,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :one
UPDATE categories
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND is_system = FALSE AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCategoryParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"user_id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteCategory, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $1,
    parent_id = $2,
    icon = $3,
    color = $4,
    display_order = $5,
    updated_at = NOW()
WHERE id = $6 AND user_id = $7 AND is_system = FALSE AND deleted_at IS NULL
RETURNING id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	Name         string        `json:"name"`
	ParentID     uuid.NullUUID `json:"parent_id"`
	Icon         *string       `json:"icon"`
	Color        *string       `json:"color"`
	DisplayOrder int32         `json:"display_order"`
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.NullUUID `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.ParentID,
		arg.Icon,
		arg.Color,
		arg.DisplayOrder,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.CategoryType,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
