// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFinalInsightsByPeriod = `-- name: CountFinalInsightsByPeriod :one
SELECT COUNT(*)::int AS count
FROM tracking_period_insights
WHERE tracking_period_id = $1
  AND calculation_phase = 'final'
`

// Used to detect whether final insights were already generated (idempotency).
func (q *Queries) CountFinalInsightsByPeriod(ctx context.Context, trackingPeriodID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFinalInsightsByPeriod, trackingPeriodID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createTrackingPeriodInsight = `-- name: CreateTrackingPeriodInsight :one
INSERT INTO tracking_period_insights (
    tracking_period_id,
    user_id,
    insight_type,
    calculation_phase,
    severity,
    title,
    message,
    action_label,
    action_target,
    data,
    related_category_id,
    related_account_id,
    related_goal_id,
    valid_from,
    valid_until
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    NOW(),
    $14
)
RETURNING id, tracking_period_id, user_id, insight_type, calculation_phase, severity, title, message, action_label, action_target, data, related_category_id, related_account_id, related_goal_id, is_dismissed, dismissed_at, valid_from, valid_until, created_at, updated_at
`

type CreateTrackingPeriodInsightParams struct {
	TrackingPeriodID  uuid.UUID          `json:"tracking_period_id"`
	UserID            uuid.UUID          `json:"user_id"`
	InsightType       string             `json:"insight_type"`
	CalculationPhase  string             `json:"calculation_phase"`
	Severity          string             `json:"severity"`
	Title             string             `json:"title"`
	Message           string             `json:"message"`
	ActionLabel       *string            `json:"action_label"`
	ActionTarget      *string            `json:"action_target"`
	Data              []byte             `json:"data"`
	RelatedCategoryID uuid.NullUUID      `json:"related_category_id"`
	RelatedAccountID  uuid.NullUUID      `json:"related_account_id"`
	RelatedGoalID     uuid.NullUUID      `json:"related_goal_id"`
	ValidUntil        pgtype.Timestamptz `json:"valid_until"`
}

func (q *Queries) CreateTrackingPeriodInsight(ctx context.Context, arg CreateTrackingPeriodInsightParams) (TrackingPeriodInsight, error) {
	row := q.db.QueryRow(ctx, createTrackingPeriodInsight,
		arg.TrackingPeriodID,
		arg.UserID,
		arg.InsightType,
		arg.CalculationPhase,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.ActionLabel,
		arg.ActionTarget,
		arg.Data,
		arg.RelatedCategoryID,
		arg.RelatedAccountID,
		arg.RelatedGoalID,
		arg.ValidUntil,
	)
	var i TrackingPeriodInsight
	err := row.Scan(
		&i.ID,
		&i.TrackingPeriodID,
		&i.UserID,
		&i.InsightType,
		&i.CalculationPhase,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.ActionLabel,
		&i.ActionTarget,
		&i.Data,
		&i.RelatedCategoryID,
		&i.RelatedAccountID,
		&i.RelatedGoalID,
		&i.IsDismissed,
		&i.DismissedAt,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDuringInsightsByPeriod = `-- name: DeleteDuringInsightsByPeriod :exec
DELETE FROM tracking_period_insights
WHERE tracking_period_id = $1
  AND user_id = $2
  AND calculation_phase = 'during'
`

type DeleteDuringInsightsByPeriodParams struct {
	TrackingPeriodID uuid.UUID `json:"tracking_period_id"`
	UserID           uuid.UUID `json:"user_id"`
}

// Deletes all "during" insights for a period. Used before regenerating them
// (replace strategy) and when closing the period (cleanup before final insights).
func (q *Queries) DeleteDuringInsightsByPeriod(ctx context.Context, arg DeleteDuringInsightsByPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteDuringInsightsByPeriod, arg.TrackingPeriodID, arg.UserID)
	return err
}

const deleteImmediateDuringInsightsByPeriod = `-- name: DeleteImmediateDuringInsightsByPeriod :exec
DELETE FROM tracking_period_insights
WHERE tracking_period_id = $1
  AND user_id = $2
  AND calculation_phase = 'during'
  AND insight_type IN ('spending_pace', 'budget_warning', 'budget_exceeded')
`

type DeleteImmediateDuringInsightsByPeriodParams struct {
	TrackingPeriodID uuid.UUID `json:"tracking_period_id"`
	UserID           uuid.UUID `json:"user_id"`
}

// Deletes only the "immediate" during insights (those recalculated on every
// transaction mutation: spending_pace, budget_warning, budget_exceeded).
// The "lazy" during insights (ant_expenses_early, unusual_expense,
// vs_previous_partial, goal_progress_alert) are preserved until the next
// lazy refresh via GET /tracking-periods/:id/insights.
func (q *Queries) DeleteImmediateDuringInsightsByPeriod(ctx context.Context, arg DeleteImmediateDuringInsightsByPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteImmediateDuringInsightsByPeriod, arg.TrackingPeriodID, arg.UserID)
	return err
}

const listDuringInsightsByPeriod = `-- name: ListDuringInsightsByPeriod :many
SELECT id, tracking_period_id, user_id, insight_type, calculation_phase, severity, title, message, action_label, action_target, data, related_category_id, related_account_id, related_goal_id, is_dismissed, dismissed_at, valid_from, valid_until, created_at, updated_at FROM tracking_period_insights
WHERE tracking_period_id = $1
  AND user_id = $2
  AND calculation_phase = 'during'
  AND is_dismissed = FALSE
ORDER BY created_at DESC
`

type ListDuringInsightsByPeriodParams struct {
	TrackingPeriodID uuid.UUID `json:"tracking_period_id"`
	UserID           uuid.UUID `json:"user_id"`
}

// Returns only the "during" (in-progress) insights for an active period, newest first.
func (q *Queries) ListDuringInsightsByPeriod(ctx context.Context, arg ListDuringInsightsByPeriodParams) ([]TrackingPeriodInsight, error) {
	rows, err := q.db.Query(ctx, listDuringInsightsByPeriod, arg.TrackingPeriodID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingPeriodInsight{}
	for rows.Next() {
		var i TrackingPeriodInsight
		if err := rows.Scan(
			&i.ID,
			&i.TrackingPeriodID,
			&i.UserID,
			&i.InsightType,
			&i.CalculationPhase,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.ActionLabel,
			&i.ActionTarget,
			&i.Data,
			&i.RelatedCategoryID,
			&i.RelatedAccountID,
			&i.RelatedGoalID,
			&i.IsDismissed,
			&i.DismissedAt,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinalInsightsByPeriod = `-- name: ListFinalInsightsByPeriod :many
SELECT id, tracking_period_id, user_id, insight_type, calculation_phase, severity, title, message, action_label, action_target, data, related_category_id, related_account_id, related_goal_id, is_dismissed, dismissed_at, valid_from, valid_until, created_at, updated_at FROM tracking_period_insights
WHERE tracking_period_id = $1
  AND user_id = $2
  AND calculation_phase = 'final'
  AND is_dismissed = FALSE
ORDER BY created_at DESC
`

type ListFinalInsightsByPeriodParams struct {
	TrackingPeriodID uuid.UUID `json:"tracking_period_id"`
	UserID           uuid.UUID `json:"user_id"`
}

// Returns only the "final" (close-time) insights for a period.
func (q *Queries) ListFinalInsightsByPeriod(ctx context.Context, arg ListFinalInsightsByPeriodParams) ([]TrackingPeriodInsight, error) {
	rows, err := q.db.Query(ctx, listFinalInsightsByPeriod, arg.TrackingPeriodID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingPeriodInsight{}
	for rows.Next() {
		var i TrackingPeriodInsight
		if err := rows.Scan(
			&i.ID,
			&i.TrackingPeriodID,
			&i.UserID,
			&i.InsightType,
			&i.CalculationPhase,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.ActionLabel,
			&i.ActionTarget,
			&i.Data,
			&i.RelatedCategoryID,
			&i.RelatedAccountID,
			&i.RelatedGoalID,
			&i.IsDismissed,
			&i.DismissedAt,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsByPeriod = `-- name: ListInsightsByPeriod :many
SELECT id, tracking_period_id, user_id, insight_type, calculation_phase, severity, title, message, action_label, action_target, data, related_category_id, related_account_id, related_goal_id, is_dismissed, dismissed_at, valid_from, valid_until, created_at, updated_at FROM tracking_period_insights
WHERE tracking_period_id = $1
  AND user_id = $2
  AND is_dismissed = FALSE
ORDER BY created_at DESC
`

type ListInsightsByPeriodParams struct {
	TrackingPeriodID uuid.UUID `json:"tracking_period_id"`
	UserID           uuid.UUID `json:"user_id"`
}

// Returns all non-dismissed insights for a period, newest first.
func (q *Queries) ListInsightsByPeriod(ctx context.Context, arg ListInsightsByPeriodParams) ([]TrackingPeriodInsight, error) {
	rows, err := q.db.Query(ctx, listInsightsByPeriod, arg.TrackingPeriodID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingPeriodInsight{}
	for rows.Next() {
		var i TrackingPeriodInsight
		if err := rows.Scan(
			&i.ID,
			&i.TrackingPeriodID,
			&i.UserID,
			&i.InsightType,
			&i.CalculationPhase,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.ActionLabel,
			&i.ActionTarget,
			&i.Data,
			&i.RelatedCategoryID,
			&i.RelatedAccountID,
			&i.RelatedGoalID,
			&i.IsDismissed,
			&i.DismissedAt,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
