// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	AccountType    string             `json:"account_type"`
	Currency       string             `json:"currency"`
	InitialBalance decimal.Decimal    `json:"initial_balance"`
	CurrentBalance decimal.Decimal    `json:"current_balance"`
	Icon           *string            `json:"icon"`
	Color          *string            `json:"color"`
	IsArchived     bool               `json:"is_archived"`
	DisplayOrder   int32              `json:"display_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Budget struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	TrackingPeriodID       uuid.UUID          `json:"tracking_period_id"`
	CategoryID             uuid.NullUUID      `json:"category_id"`
	Amount                 decimal.Decimal    `json:"amount"`
	Currency               string             `json:"currency"`
	AlertThresholdWarning  decimal.Decimal    `json:"alert_threshold_warning"`
	AlertThresholdCritical decimal.Decimal    `json:"alert_threshold_critical"`
	Notes                  *string            `json:"notes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.NullUUID      `json:"user_id"`
	ParentID     uuid.NullUUID      `json:"parent_id"`
	Name         string             `json:"name"`
	CategoryType string             `json:"category_type"`
	Icon         *string            `json:"icon"`
	Color        *string            `json:"color"`
	IsSystem     bool               `json:"is_system"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type RecurringTransaction struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	AccountID          uuid.UUID          `json:"account_id"`
	CategoryID         uuid.NullUUID      `json:"category_id"`
	Name               string             `json:"name"`
	TransactionType    string             `json:"transaction_type"`
	Amount             decimal.Decimal    `json:"amount"`
	Currency           string             `json:"currency"`
	Description        *string            `json:"description"`
	Frequency          string             `json:"frequency"`
	CustomIntervalDays *int32             `json:"custom_interval_days"`
	DayOfMonth         *int16             `json:"day_of_month"`
	DayOfWeek          *int16             `json:"day_of_week"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	LastGeneratedDate  pgtype.Date        `json:"last_generated_date"`
	NextDueDate        pgtype.Date        `json:"next_due_date"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SavingsGoal struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	Icon            *string            `json:"icon"`
	Color           *string            `json:"color"`
	TargetAmount    decimal.Decimal    `json:"target_amount"`
	CurrentAmount   decimal.Decimal    `json:"current_amount"`
	Currency        string             `json:"currency"`
	StartDate       pgtype.Date        `json:"start_date"`
	TargetDate      pgtype.Date        `json:"target_date"`
	Status          string             `json:"status"`
	LinkedAccountID uuid.NullUUID      `json:"linked_account_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AchievedAt      pgtype.Timestamptz `json:"achieved_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type SavingsGoalContribution struct {
	ID               uuid.UUID          `json:"id"`
	SavingsGoalID    uuid.UUID          `json:"savings_goal_id"`
	UserID           uuid.UUID          `json:"user_id"`
	TrackingPeriodID uuid.UUID          `json:"tracking_period_id"`
	TransactionID    uuid.NullUUID      `json:"transaction_id"`
	Amount           decimal.Decimal    `json:"amount"`
	ContributionDate pgtype.Date        `json:"contribution_date"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TrackingPeriod struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	Status             string             `json:"status"`
	SequenceNumber     int32              `json:"sequence_number"`
	ConfigStartDay     int16              `json:"config_start_day"`
	ConfigDurationDays int16              `json:"config_duration_days"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ConfigPeriodMode   string             `json:"config_period_mode"`
	IsTransition       bool               `json:"is_transition"`
}

type TrackingPeriodInsight struct {
	ID                uuid.UUID          `json:"id"`
	TrackingPeriodID  uuid.UUID          `json:"tracking_period_id"`
	UserID            uuid.UUID          `json:"user_id"`
	InsightType       string             `json:"insight_type"`
	CalculationPhase  string             `json:"calculation_phase"`
	Severity          string             `json:"severity"`
	Title             string             `json:"title"`
	Message           string             `json:"message"`
	ActionLabel       *string            `json:"action_label"`
	ActionTarget      *string            `json:"action_target"`
	Data              []byte             `json:"data"`
	RelatedCategoryID uuid.NullUUID      `json:"related_category_id"`
	RelatedAccountID  uuid.NullUUID      `json:"related_account_id"`
	RelatedGoalID     uuid.NullUUID      `json:"related_goal_id"`
	IsDismissed       bool               `json:"is_dismissed"`
	DismissedAt       pgtype.Timestamptz `json:"dismissed_at"`
	ValidFrom         pgtype.Timestamptz `json:"valid_from"`
	ValidUntil        pgtype.Timestamptz `json:"valid_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TrackingPeriodSummary struct {
	ID                       uuid.UUID           `json:"id"`
	TrackingPeriodID         uuid.UUID           `json:"tracking_period_id"`
	UserID                   uuid.UUID           `json:"user_id"`
	TotalIncome              decimal.Decimal     `json:"total_income"`
	TotalExpenses            decimal.Decimal     `json:"total_expenses"`
	TotalTransfers           decimal.Decimal     `json:"total_transfers"`
	NetSavings               decimal.Decimal     `json:"net_savings"`
	SavingsRate              decimal.NullDecimal `json:"savings_rate"`
	TransactionCount         int32               `json:"transaction_count"`
	ExpenseTransactionCount  int32               `json:"expense_transaction_count"`
	IncomeTransactionCount   int32               `json:"income_transaction_count"`
	TopExpenseCategoryID     uuid.NullUUID       `json:"top_expense_category_id"`
	TopExpenseCategoryAmount decimal.NullDecimal `json:"top_expense_category_amount"`
	ExpenseByCategory        []byte              `json:"expense_by_category"`
	IncomeByCategory         []byte              `json:"income_by_category"`
	ExpenseByAccount         []byte              `json:"expense_by_account"`
	ExpenseByDay             []byte              `json:"expense_by_day"`
	BudgetPerformance        []byte              `json:"budget_performance"`
	GoalContributionsTotal   decimal.Decimal     `json:"goal_contributions_total"`
	VsPreviousPeriod         []byte              `json:"vs_previous_period"`
	CalculatedAt             pgtype.Timestamptz  `json:"calculated_at"`
}

type Transaction struct {
	ID                     uuid.UUID           `json:"id"`
	UserID                 uuid.UUID           `json:"user_id"`
	TrackingPeriodID       uuid.UUID           `json:"tracking_period_id"`
	AccountID              uuid.UUID           `json:"account_id"`
	CategoryID             uuid.NullUUID       `json:"category_id"`
	TransactionType        string              `json:"transaction_type"`
	Amount                 decimal.Decimal     `json:"amount"`
	Currency               string              `json:"currency"`
	Description            *string             `json:"description"`
	Notes                  *string             `json:"notes"`
	TransactionDate        pgtype.Date         `json:"transaction_date"`
	TransferAccountID      uuid.NullUUID       `json:"transfer_account_id"`
	AiCategorized          bool                `json:"ai_categorized"`
	AiConfidence           decimal.NullDecimal `json:"ai_confidence"`
	AiSuggestedCategoryID  uuid.NullUUID       `json:"ai_suggested_category_id"`
	VoiceInput             bool                `json:"voice_input"`
	RawVoiceText           *string             `json:"raw_voice_text"`
	LocationLat            decimal.NullDecimal `json:"location_lat"`
	LocationLng            decimal.NullDecimal `json:"location_lng"`
	ClientID               *string             `json:"client_id"`
	SyncedAt               pgtype.Timestamptz  `json:"synced_at"`
	CreatedAt              pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz  `json:"deleted_at"`
	RecurringTransactionID uuid.NullUUID       `json:"recurring_transaction_id"`
	OccurrenceDate         pgtype.Date         `json:"occurrence_date"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	FullName     *string            `json:"full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	PasswordHash *string            `json:"password_hash"`
}

type UserAiSetting struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        string             `json:"provider"`
	ApiKeyEncrypted []byte             `json:"api_key_encrypted"`
	BaseUrl         *string            `json:"base_url"`
	Model           *string            `json:"model"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserSetting struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	TrackingStartDay     int16              `json:"tracking_start_day"`
	TrackingDurationDays int16              `json:"tracking_duration_days"`
	DefaultCurrency      string             `json:"default_currency"`
	CountryCode          string             `json:"country_code"`
	Locale               string             `json:"locale"`
	Theme                string             `json:"theme"`
	DefaultPeriodView    string             `json:"default_period_view"`
	SubscriptionTier     string             `json:"subscription_tier"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TrackingPeriodMode   string             `json:"tracking_period_mode"`
}
