// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AdjustAccountBalance(ctx context.Context, arg AdjustAccountBalanceParams) error
	// After materialising one occurrence, update the template:
	//   - last_generated_date ← the occurrence date just generated
	//   - next_due_date       ← the next scheduled occurrence (computed by Go)
	//   - is_active           ← caller sets to FALSE when end_date is exhausted
	AdvanceRecurringTransaction(ctx context.Context, arg AdvanceRecurringTransactionParams) (RecurringTransaction, error)
	// Atomically adds the contribution amount to current_amount. If the resulting
	// current_amount meets or exceeds target_amount and the goal is not already
	// achieved, marks it achieved and sets achieved_at = NOW().
	// NOTE: CASE expressions reference OLD column values (pre-update), so
	// current_amount + $amount correctly computes the post-update total.
	ApplyGoalContribution(ctx context.Context, arg ApplyGoalContributionParams) (SavingsGoal, error)
	ClosePeriod(ctx context.Context, id uuid.UUID) (TrackingPeriod, error)
	// Used to detect whether final insights were already generated (idempotency).
	CountFinalInsightsByPeriod(ctx context.Context, trackingPeriodID uuid.UUID) (int32, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	CreateSavingsGoalContribution(ctx context.Context, arg CreateSavingsGoalContributionParams) (SavingsGoalContribution, error)
	CreateTrackingPeriod(ctx context.Context, arg CreateTrackingPeriodParams) (TrackingPeriod, error)
	CreateTrackingPeriodInsight(ctx context.Context, arg CreateTrackingPeriodInsightParams) (TrackingPeriodInsight, error)
	CreateTrackingPeriodSummary(ctx context.Context, arg CreateTrackingPeriodSummaryParams) (TrackingPeriodSummary, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error)
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (uuid.UUID, error)
	ExpenseByAccount(ctx context.Context, trackingPeriodID uuid.UUID) ([]ExpenseByAccountRow, error)
	// Groups expense transactions in the period by category. Returns category_id
	// (nullable), category name (nullable — NULL when uncategorized), and total.
	ExpenseByCategory(ctx context.Context, trackingPeriodID uuid.UUID) ([]ExpenseByCategoryRow, error)
	// Daily expense totals for the period, ordered chronologically.
	ExpenseByDay(ctx context.Context, trackingPeriodID uuid.UUID) ([]ExpenseByDayRow, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetActiveTrackingPeriod(ctx context.Context, userID uuid.UUID) (TrackingPeriod, error)
	GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error)
	// A category is usable if it belongs to the user or is a system category.
	GetCategoryForUser(ctx context.Context, arg GetCategoryForUserParams) (Category, error)
	// Only the user's own (non-system) category; used for update/delete.
	GetOwnedCategory(ctx context.Context, arg GetOwnedCategoryParams) (Category, error)
	// Returns the immediately preceding closed period for the same user.
	GetPreviousTrackingPeriod(ctx context.Context, arg GetPreviousTrackingPeriodParams) (TrackingPeriod, error)
	GetRecurringTransaction(ctx context.Context, arg GetRecurringTransactionParams) (RecurringTransaction, error)
	// Returns a usable (not revoked, not expired) refresh token by its hash.
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSavingsGoal(ctx context.Context, arg GetSavingsGoalParams) (SavingsGoal, error)
	GetTopExpenseCategory(ctx context.Context, trackingPeriodID uuid.UUID) (GetTopExpenseCategoryRow, error)
	GetTrackingPeriodByID(ctx context.Context, id uuid.UUID) (TrackingPeriod, error)
	// Like GetTrackingPeriodByID but scoped to the owner — safe to expose directly.
	GetTrackingPeriodForUser(ctx context.Context, arg GetTrackingPeriodForUserParams) (TrackingPeriod, error)
	GetTrackingPeriodSummary(ctx context.Context, trackingPeriodID uuid.UUID) (TrackingPeriodSummary, error)
	// Returns the snapshot summary for a closed period (used for vs_previous).
	GetTrackingPeriodSummaryForPeriod(ctx context.Context, trackingPeriodID uuid.UUID) (TrackingPeriodSummary, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserSettingsByUserID(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	// Total savings goal contributions that were recorded within a tracking period.
	GoalContributionsTotalForPeriod(ctx context.Context, trackingPeriodID uuid.UUID) (decimal.Decimal, error)
	// Idempotency guard: returns TRUE if a non-deleted transaction already exists
	// for this (template, occurrence_date) pair, avoiding duplicate generation
	// on re-runs. We use occurrence_date (the original scheduled date) rather
	// than transaction_date (which may be clamped to the period bounds).
	HasRecurringTransactionForDate(ctx context.Context, arg HasRecurringTransactionForDateParams) (bool, error)
	IncomeByCategory(ctx context.Context, trackingPeriodID uuid.UUID) ([]IncomeByCategoryRow, error)
	ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error)
	// Internal: used when copying budgets onto a freshly generated period.
	ListBudgetsByPeriod(ctx context.Context, trackingPeriodID uuid.UUID) ([]Budget, error)
	ListBudgetsForUser(ctx context.Context, arg ListBudgetsForUserParams) ([]Budget, error)
	// System categories plus the user's own, usable for selection.
	ListCategoriesForUser(ctx context.Context, userID uuid.NullUUID) ([]Category, error)
	ListContributionsForGoal(ctx context.Context, arg ListContributionsForGoalParams) ([]SavingsGoalContribution, error)
	// Active periods whose end_date is strictly before the given date (i.e. over).
	ListDueActivePeriods(ctx context.Context, endDate pgtype.Date) ([]TrackingPeriod, error)
	// Returns all active, non-deleted recurring templates whose next_due_date is
	// on or before the given date. Used by the recurrence engine (scheduler +
	// lazy trigger) to find templates that need materialization.
	ListDueRecurringTransactions(ctx context.Context, dueBefore pgtype.Date) ([]RecurringTransaction, error)
	// Returns only the "final" (close-time) insights for a period.
	ListFinalInsightsByPeriod(ctx context.Context, arg ListFinalInsightsByPeriodParams) ([]TrackingPeriodInsight, error)
	// Returns all non-dismissed insights for a period, newest first.
	ListInsightsByPeriod(ctx context.Context, arg ListInsightsByPeriodParams) ([]TrackingPeriodInsight, error)
	ListRecurringTransactionsForUser(ctx context.Context, userID uuid.UUID) ([]RecurringTransaction, error)
	ListSavingsGoalsForUser(ctx context.Context, userID uuid.UUID) ([]SavingsGoal, error)
	ListSystemCategories(ctx context.Context) ([]Category, error)
	ListTrackingPeriodsByUser(ctx context.Context, userID uuid.UUID) ([]TrackingPeriod, error)
	ListTransactionsByPeriod(ctx context.Context, arg ListTransactionsByPeriodParams) ([]Transaction, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (uuid.UUID, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (uuid.UUID, error)
	SoftDeleteRecurringTransaction(ctx context.Context, arg SoftDeleteRecurringTransactionParams) (uuid.UUID, error)
	SoftDeleteSavingsGoal(ctx context.Context, arg SoftDeleteSavingsGoalParams) (uuid.UUID, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error)
	SummarizePeriodTotals(ctx context.Context, trackingPeriodID uuid.UUID) (SummarizePeriodTotalsRow, error)
	// Same aggregates as SummarizePeriodTotals but filtered to [from_date, to_date].
	// Used to compute biweekly / weekly sub-period breakdowns on the fly.
	SummarizePeriodTotalsInRange(ctx context.Context, arg SummarizePeriodTotalsInRangeParams) (SummarizePeriodTotalsInRangeRow, error)
	// Returns the top description values by total expense amount.
	// Only rows with a non-empty description are included so purely note-based
	// transactions do not pollute the merchant list.
	TopMerchants(ctx context.Context, trackingPeriodID uuid.UUID) ([]TopMerchantsRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error)
	UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error)
	// Populates the JSONB breakdown columns on an existing summary row. Called
	// after the row is created so we can compute breakdowns in Go and set them
	// in a second step without reopening the creation transaction.
	UpdateTrackingPeriodSummaryBreakdowns(ctx context.Context, arg UpdateTrackingPeriodSummaryBreakdownsParams) (TrackingPeriodSummary, error)
	// tracking_period_id is intentionally NOT updatable (a transaction stays in its
	// period). The validate_transaction_period trigger re-checks date/period here.
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
