// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdjustAccountBalance(ctx context.Context, arg AdjustAccountBalanceParams) error
	// After materialising one occurrence, update the template:
	//   - last_generated_date ← the occurrence date just generated
	//   - next_due_date       ← the next scheduled occurrence (computed by Go)
	//   - is_active           ← caller sets to FALSE when end_date is exhausted
	AdvanceRecurringTransaction(ctx context.Context, arg AdvanceRecurringTransactionParams) (RecurringTransaction, error)
	// Atomically adds the contribution amount to current_amount. If the resulting
	// current_amount meets or exceeds target_amount and the goal is not already
	// achieved, marks it achieved and sets achieved_at = NOW().
	// NOTE: CASE expressions reference OLD column values (pre-update), so
	// current_amount + $amount correctly computes the post-update total.
	ApplyGoalContribution(ctx context.Context, arg ApplyGoalContributionParams) (SavingsGoal, error)
	ClosePeriod(ctx context.Context, id uuid.UUID) (TrackingPeriod, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	CreateSavingsGoalContribution(ctx context.Context, arg CreateSavingsGoalContributionParams) (SavingsGoalContribution, error)
	CreateTrackingPeriod(ctx context.Context, arg CreateTrackingPeriodParams) (TrackingPeriod, error)
	CreateTrackingPeriodSummary(ctx context.Context, arg CreateTrackingPeriodSummaryParams) (TrackingPeriodSummary, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error)
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (uuid.UUID, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetActiveTrackingPeriod(ctx context.Context, userID uuid.UUID) (TrackingPeriod, error)
	GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error)
	// A category is usable if it belongs to the user or is a system category.
	GetCategoryForUser(ctx context.Context, arg GetCategoryForUserParams) (Category, error)
	// Only the user's own (non-system) category; used for update/delete.
	GetOwnedCategory(ctx context.Context, arg GetOwnedCategoryParams) (Category, error)
	GetRecurringTransaction(ctx context.Context, arg GetRecurringTransactionParams) (RecurringTransaction, error)
	// Returns a usable (not revoked, not expired) refresh token by its hash.
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSavingsGoal(ctx context.Context, arg GetSavingsGoalParams) (SavingsGoal, error)
	GetTopExpenseCategory(ctx context.Context, trackingPeriodID uuid.UUID) (GetTopExpenseCategoryRow, error)
	GetTrackingPeriodByID(ctx context.Context, id uuid.UUID) (TrackingPeriod, error)
	// Like GetTrackingPeriodByID but scoped to the owner — safe to expose directly.
	GetTrackingPeriodForUser(ctx context.Context, arg GetTrackingPeriodForUserParams) (TrackingPeriod, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserSettingsByUserID(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	// Idempotency guard: returns TRUE if a non-deleted transaction already exists
	// for this (template, occurrence_date) pair, avoiding duplicate generation
	// on re-runs. We use occurrence_date (the original scheduled date) rather
	// than transaction_date (which may be clamped to the period bounds).
	HasRecurringTransactionForDate(ctx context.Context, arg HasRecurringTransactionForDateParams) (bool, error)
	ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error)
	// Internal: used when copying budgets onto a freshly generated period.
	ListBudgetsByPeriod(ctx context.Context, trackingPeriodID uuid.UUID) ([]Budget, error)
	ListBudgetsForUser(ctx context.Context, arg ListBudgetsForUserParams) ([]Budget, error)
	// System categories plus the user's own, usable for selection.
	ListCategoriesForUser(ctx context.Context, userID uuid.NullUUID) ([]Category, error)
	ListContributionsForGoal(ctx context.Context, arg ListContributionsForGoalParams) ([]SavingsGoalContribution, error)
	// Active periods whose end_date is strictly before the given date (i.e. over).
	ListDueActivePeriods(ctx context.Context, endDate pgtype.Date) ([]TrackingPeriod, error)
	// Returns all active, non-deleted recurring templates whose next_due_date is
	// on or before the given date. Used by the recurrence engine (scheduler +
	// lazy trigger) to find templates that need materialization.
	ListDueRecurringTransactions(ctx context.Context, dueBefore pgtype.Date) ([]RecurringTransaction, error)
	ListRecurringTransactionsForUser(ctx context.Context, userID uuid.UUID) ([]RecurringTransaction, error)
	ListSavingsGoalsForUser(ctx context.Context, userID uuid.UUID) ([]SavingsGoal, error)
	ListSystemCategories(ctx context.Context) ([]Category, error)
	ListTrackingPeriodsByUser(ctx context.Context, userID uuid.UUID) ([]TrackingPeriod, error)
	ListTransactionsByPeriod(ctx context.Context, arg ListTransactionsByPeriodParams) ([]Transaction, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (uuid.UUID, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (uuid.UUID, error)
	SoftDeleteRecurringTransaction(ctx context.Context, arg SoftDeleteRecurringTransactionParams) (uuid.UUID, error)
	SoftDeleteSavingsGoal(ctx context.Context, arg SoftDeleteSavingsGoalParams) (uuid.UUID, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error)
	SummarizePeriodTotals(ctx context.Context, trackingPeriodID uuid.UUID) (SummarizePeriodTotalsRow, error)
	// Same aggregates as SummarizePeriodTotals but filtered to [from_date, to_date].
	// Used to compute biweekly / weekly sub-period breakdowns on the fly.
	SummarizePeriodTotalsInRange(ctx context.Context, arg SummarizePeriodTotalsInRangeParams) (SummarizePeriodTotalsInRangeRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error)
	UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error)
	// tracking_period_id is intentionally NOT updatable (a transaction stays in its
	// period). The validate_transaction_period trigger re-checks date/period here.
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
