// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createRecurringTransaction = `-- name: CreateRecurringTransaction :one
INSERT INTO recurring_transactions (
    user_id, account_id, category_id, name, transaction_type, amount, currency,
    description, frequency, custom_interval_days, day_of_month, day_of_week,
    start_date, end_date, next_due_date, is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id, user_id, account_id, category_id, name, transaction_type, amount, currency, description, frequency, custom_interval_days, day_of_month, day_of_week, start_date, end_date, last_generated_date, next_due_date, is_active, created_at, updated_at, deleted_at
`

type CreateRecurringTransactionParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	AccountID          uuid.UUID       `json:"account_id"`
	CategoryID         uuid.NullUUID   `json:"category_id"`
	Name               string          `json:"name"`
	TransactionType    string          `json:"transaction_type"`
	Amount             decimal.Decimal `json:"amount"`
	Currency           string          `json:"currency"`
	Description        *string         `json:"description"`
	Frequency          string          `json:"frequency"`
	CustomIntervalDays *int32          `json:"custom_interval_days"`
	DayOfMonth         *int16          `json:"day_of_month"`
	DayOfWeek          *int16          `json:"day_of_week"`
	StartDate          pgtype.Date     `json:"start_date"`
	EndDate            pgtype.Date     `json:"end_date"`
	NextDueDate        pgtype.Date     `json:"next_due_date"`
	IsActive           bool            `json:"is_active"`
}

func (q *Queries) CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, createRecurringTransaction,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Name,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Frequency,
		arg.CustomIntervalDays,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.StartDate,
		arg.EndDate,
		arg.NextDueDate,
		arg.IsActive,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Name,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.StartDate,
		&i.EndDate,
		&i.LastGeneratedDate,
		&i.NextDueDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecurringTransaction = `-- name: GetRecurringTransaction :one
SELECT id, user_id, account_id, category_id, name, transaction_type, amount, currency, description, frequency, custom_interval_days, day_of_month, day_of_week, start_date, end_date, last_generated_date, next_due_date, is_active, created_at, updated_at, deleted_at FROM recurring_transactions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetRecurringTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRecurringTransaction(ctx context.Context, arg GetRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, getRecurringTransaction, arg.ID, arg.UserID)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Name,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.StartDate,
		&i.EndDate,
		&i.LastGeneratedDate,
		&i.NextDueDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRecurringTransactionsForUser = `-- name: ListRecurringTransactionsForUser :many
SELECT id, user_id, account_id, category_id, name, transaction_type, amount, currency, description, frequency, custom_interval_days, day_of_month, day_of_week, start_date, end_date, last_generated_date, next_due_date, is_active, created_at, updated_at, deleted_at FROM recurring_transactions
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRecurringTransactionsForUser(ctx context.Context, userID uuid.UUID) ([]RecurringTransaction, error) {
	rows, err := q.db.Query(ctx, listRecurringTransactionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringTransaction{}
	for rows.Next() {
		var i RecurringTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Name,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Frequency,
			&i.CustomIntervalDays,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.StartDate,
			&i.EndDate,
			&i.LastGeneratedDate,
			&i.NextDueDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRecurringTransaction = `-- name: SoftDeleteRecurringTransaction :one
UPDATE recurring_transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteRecurringTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteRecurringTransaction(ctx context.Context, arg SoftDeleteRecurringTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteRecurringTransaction, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRecurringTransaction = `-- name: UpdateRecurringTransaction :one
UPDATE recurring_transactions
SET account_id          = $1,
    category_id         = $2,
    name                = $3,
    transaction_type    = $4,
    amount              = $5,
    currency            = $6,
    description         = $7,
    frequency           = $8,
    custom_interval_days = $9,
    day_of_month        = $10,
    day_of_week         = $11,
    start_date          = $12,
    end_date            = $13,
    next_due_date       = $14,
    is_active           = $15,
    updated_at          = NOW()
WHERE id = $16 AND user_id = $17 AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, name, transaction_type, amount, currency, description, frequency, custom_interval_days, day_of_month, day_of_week, start_date, end_date, last_generated_date, next_due_date, is_active, created_at, updated_at, deleted_at
`

type UpdateRecurringTransactionParams struct {
	AccountID          uuid.UUID       `json:"account_id"`
	CategoryID         uuid.NullUUID   `json:"category_id"`
	Name               string          `json:"name"`
	TransactionType    string          `json:"transaction_type"`
	Amount             decimal.Decimal `json:"amount"`
	Currency           string          `json:"currency"`
	Description        *string         `json:"description"`
	Frequency          string          `json:"frequency"`
	CustomIntervalDays *int32          `json:"custom_interval_days"`
	DayOfMonth         *int16          `json:"day_of_month"`
	DayOfWeek          *int16          `json:"day_of_week"`
	StartDate          pgtype.Date     `json:"start_date"`
	EndDate            pgtype.Date     `json:"end_date"`
	NextDueDate        pgtype.Date     `json:"next_due_date"`
	IsActive           bool            `json:"is_active"`
	ID                 uuid.UUID       `json:"id"`
	UserID             uuid.UUID       `json:"user_id"`
}

func (q *Queries) UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateRecurringTransaction,
		arg.AccountID,
		arg.CategoryID,
		arg.Name,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Frequency,
		arg.CustomIntervalDays,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.StartDate,
		arg.EndDate,
		arg.NextDueDate,
		arg.IsActive,
		arg.ID,
		arg.UserID,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Name,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Frequency,
		&i.CustomIntervalDays,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.StartDate,
		&i.EndDate,
		&i.LastGeneratedDate,
		&i.NextDueDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
