// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: savings_goals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const applyGoalContribution = `-- name: ApplyGoalContribution :one
UPDATE savings_goals
SET current_amount = current_amount + $1,
    status = CASE
        WHEN current_amount + $1 >= target_amount AND status != 'achieved'
        THEN 'achieved'
        ELSE status
    END,
    achieved_at = CASE
        WHEN current_amount + $1 >= target_amount AND status != 'achieved'
        THEN NOW()
        ELSE achieved_at
    END,
    updated_at = NOW()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, user_id, name, description, icon, color, target_amount, current_amount, currency, start_date, target_date, status, linked_account_id, created_at, updated_at, achieved_at, deleted_at
`

type ApplyGoalContributionParams struct {
	Amount decimal.Decimal `json:"amount"`
	ID     uuid.UUID       `json:"id"`
	UserID uuid.UUID       `json:"user_id"`
}

// Atomically adds the contribution amount to current_amount. If the resulting
// current_amount meets or exceeds target_amount and the goal is not already
// achieved, marks it achieved and sets achieved_at = NOW().
// NOTE: CASE expressions reference OLD column values (pre-update), so
// current_amount + $amount correctly computes the post-update total.
func (q *Queries) ApplyGoalContribution(ctx context.Context, arg ApplyGoalContributionParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, applyGoalContribution, arg.Amount, arg.ID, arg.UserID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Currency,
		&i.StartDate,
		&i.TargetDate,
		&i.Status,
		&i.LinkedAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AchievedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (
    user_id, name, description, icon, color,
    target_amount, currency, start_date, target_date, linked_account_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, name, description, icon, color, target_amount, current_amount, currency, start_date, target_date, status, linked_account_id, created_at, updated_at, achieved_at, deleted_at
`

type CreateSavingsGoalParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	Name            string          `json:"name"`
	Description     *string         `json:"description"`
	Icon            *string         `json:"icon"`
	Color           *string         `json:"color"`
	TargetAmount    decimal.Decimal `json:"target_amount"`
	Currency        string          `json:"currency"`
	StartDate       pgtype.Date     `json:"start_date"`
	TargetDate      pgtype.Date     `json:"target_date"`
	LinkedAccountID uuid.NullUUID   `json:"linked_account_id"`
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.TargetAmount,
		arg.Currency,
		arg.StartDate,
		arg.TargetDate,
		arg.LinkedAccountID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Currency,
		&i.StartDate,
		&i.TargetDate,
		&i.Status,
		&i.LinkedAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AchievedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSavingsGoalContribution = `-- name: CreateSavingsGoalContribution :one
INSERT INTO savings_goal_contributions (
    savings_goal_id, user_id, tracking_period_id, amount, contribution_date, notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, savings_goal_id, user_id, tracking_period_id, transaction_id, amount, contribution_date, notes, created_at, updated_at
`

type CreateSavingsGoalContributionParams struct {
	SavingsGoalID    uuid.UUID       `json:"savings_goal_id"`
	UserID           uuid.UUID       `json:"user_id"`
	TrackingPeriodID uuid.UUID       `json:"tracking_period_id"`
	Amount           decimal.Decimal `json:"amount"`
	ContributionDate pgtype.Date     `json:"contribution_date"`
	Notes            *string         `json:"notes"`
}

func (q *Queries) CreateSavingsGoalContribution(ctx context.Context, arg CreateSavingsGoalContributionParams) (SavingsGoalContribution, error) {
	row := q.db.QueryRow(ctx, createSavingsGoalContribution,
		arg.SavingsGoalID,
		arg.UserID,
		arg.TrackingPeriodID,
		arg.Amount,
		arg.ContributionDate,
		arg.Notes,
	)
	var i SavingsGoalContribution
	err := row.Scan(
		&i.ID,
		&i.SavingsGoalID,
		&i.UserID,
		&i.TrackingPeriodID,
		&i.TransactionID,
		&i.Amount,
		&i.ContributionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavingsGoal = `-- name: GetSavingsGoal :one
SELECT id, user_id, name, description, icon, color, target_amount, current_amount, currency, start_date, target_date, status, linked_account_id, created_at, updated_at, achieved_at, deleted_at FROM savings_goals
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetSavingsGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSavingsGoal(ctx context.Context, arg GetSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getSavingsGoal, arg.ID, arg.UserID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Currency,
		&i.StartDate,
		&i.TargetDate,
		&i.Status,
		&i.LinkedAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AchievedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContributionsForGoal = `-- name: ListContributionsForGoal :many
SELECT id, savings_goal_id, user_id, tracking_period_id, transaction_id, amount, contribution_date, notes, created_at, updated_at FROM savings_goal_contributions
WHERE savings_goal_id = $1 AND user_id = $2
ORDER BY contribution_date DESC, created_at DESC
`

type ListContributionsForGoalParams struct {
	SavingsGoalID uuid.UUID `json:"savings_goal_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) ListContributionsForGoal(ctx context.Context, arg ListContributionsForGoalParams) ([]SavingsGoalContribution, error) {
	rows, err := q.db.Query(ctx, listContributionsForGoal, arg.SavingsGoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoalContribution{}
	for rows.Next() {
		var i SavingsGoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.SavingsGoalID,
			&i.UserID,
			&i.TrackingPeriodID,
			&i.TransactionID,
			&i.Amount,
			&i.ContributionDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoalsForUser = `-- name: ListSavingsGoalsForUser :many
SELECT id, user_id, name, description, icon, color, target_amount, current_amount, currency, start_date, target_date, status, linked_account_id, created_at, updated_at, achieved_at, deleted_at FROM savings_goals
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSavingsGoalsForUser(ctx context.Context, userID uuid.UUID) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoalsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Currency,
			&i.StartDate,
			&i.TargetDate,
			&i.Status,
			&i.LinkedAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AchievedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSavingsGoal = `-- name: SoftDeleteSavingsGoal :one
UPDATE savings_goals
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteSavingsGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteSavingsGoal(ctx context.Context, arg SoftDeleteSavingsGoalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteSavingsGoal, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals
SET name             = $1,
    description      = $2,
    icon             = $3,
    color            = $4,
    target_amount    = $5,
    target_date      = $6,
    status           = $7,
    linked_account_id = $8,
    updated_at       = NOW()
WHERE id = $9 AND user_id = $10 AND deleted_at IS NULL
RETURNING id, user_id, name, description, icon, color, target_amount, current_amount, currency, start_date, target_date, status, linked_account_id, created_at, updated_at, achieved_at, deleted_at
`

type UpdateSavingsGoalParams struct {
	Name            string          `json:"name"`
	Description     *string         `json:"description"`
	Icon            *string         `json:"icon"`
	Color           *string         `json:"color"`
	TargetAmount    decimal.Decimal `json:"target_amount"`
	TargetDate      pgtype.Date     `json:"target_date"`
	Status          string          `json:"status"`
	LinkedAccountID uuid.NullUUID   `json:"linked_account_id"`
	ID              uuid.UUID       `json:"id"`
	UserID          uuid.UUID       `json:"user_id"`
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.TargetAmount,
		arg.TargetDate,
		arg.Status,
		arg.LinkedAccountID,
		arg.ID,
		arg.UserID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Currency,
		&i.StartDate,
		&i.TargetDate,
		&i.Status,
		&i.LinkedAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AchievedAt,
		&i.DeletedAt,
	)
	return i, err
}
