// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTrackingPeriodSummary = `-- name: CreateTrackingPeriodSummary :one
INSERT INTO tracking_period_summaries (
    tracking_period_id, user_id,
    total_income, total_expenses, total_transfers, net_savings, savings_rate,
    transaction_count, expense_transaction_count, income_transaction_count,
    top_expense_category_id, top_expense_category_amount
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, tracking_period_id, user_id, total_income, total_expenses, total_transfers, net_savings, savings_rate, transaction_count, expense_transaction_count, income_transaction_count, top_expense_category_id, top_expense_category_amount, expense_by_category, income_by_category, expense_by_account, expense_by_day, budget_performance, goal_contributions_total, vs_previous_period, calculated_at
`

type CreateTrackingPeriodSummaryParams struct {
	TrackingPeriodID         uuid.UUID           `json:"tracking_period_id"`
	UserID                   uuid.UUID           `json:"user_id"`
	TotalIncome              decimal.Decimal     `json:"total_income"`
	TotalExpenses            decimal.Decimal     `json:"total_expenses"`
	TotalTransfers           decimal.Decimal     `json:"total_transfers"`
	NetSavings               decimal.Decimal     `json:"net_savings"`
	SavingsRate              decimal.NullDecimal `json:"savings_rate"`
	TransactionCount         int32               `json:"transaction_count"`
	ExpenseTransactionCount  int32               `json:"expense_transaction_count"`
	IncomeTransactionCount   int32               `json:"income_transaction_count"`
	TopExpenseCategoryID     uuid.NullUUID       `json:"top_expense_category_id"`
	TopExpenseCategoryAmount decimal.NullDecimal `json:"top_expense_category_amount"`
}

func (q *Queries) CreateTrackingPeriodSummary(ctx context.Context, arg CreateTrackingPeriodSummaryParams) (TrackingPeriodSummary, error) {
	row := q.db.QueryRow(ctx, createTrackingPeriodSummary,
		arg.TrackingPeriodID,
		arg.UserID,
		arg.TotalIncome,
		arg.TotalExpenses,
		arg.TotalTransfers,
		arg.NetSavings,
		arg.SavingsRate,
		arg.TransactionCount,
		arg.ExpenseTransactionCount,
		arg.IncomeTransactionCount,
		arg.TopExpenseCategoryID,
		arg.TopExpenseCategoryAmount,
	)
	var i TrackingPeriodSummary
	err := row.Scan(
		&i.ID,
		&i.TrackingPeriodID,
		&i.UserID,
		&i.TotalIncome,
		&i.TotalExpenses,
		&i.TotalTransfers,
		&i.NetSavings,
		&i.SavingsRate,
		&i.TransactionCount,
		&i.ExpenseTransactionCount,
		&i.IncomeTransactionCount,
		&i.TopExpenseCategoryID,
		&i.TopExpenseCategoryAmount,
		&i.ExpenseByCategory,
		&i.IncomeByCategory,
		&i.ExpenseByAccount,
		&i.ExpenseByDay,
		&i.BudgetPerformance,
		&i.GoalContributionsTotal,
		&i.VsPreviousPeriod,
		&i.CalculatedAt,
	)
	return i, err
}

const getTopExpenseCategory = `-- name: GetTopExpenseCategory :one
SELECT category_id, SUM(amount)::numeric AS total
FROM transactions
WHERE tracking_period_id = $1
  AND transaction_type = 'expense'
  AND deleted_at IS NULL
  AND category_id IS NOT NULL
GROUP BY category_id
ORDER BY total DESC
LIMIT 1
`

type GetTopExpenseCategoryRow struct {
	CategoryID uuid.NullUUID   `json:"category_id"`
	Total      decimal.Decimal `json:"total"`
}

func (q *Queries) GetTopExpenseCategory(ctx context.Context, trackingPeriodID uuid.UUID) (GetTopExpenseCategoryRow, error) {
	row := q.db.QueryRow(ctx, getTopExpenseCategory, trackingPeriodID)
	var i GetTopExpenseCategoryRow
	err := row.Scan(&i.CategoryID, &i.Total)
	return i, err
}

const summarizePeriodTotals = `-- name: SummarizePeriodTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'income'), 0)::numeric  AS total_income,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'expense'), 0)::numeric AS total_expenses,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'transfer'), 0)::numeric AS total_transfers,
    COUNT(*)::int                                                AS transaction_count,
    COUNT(*) FILTER (WHERE transaction_type = 'expense')::int    AS expense_transaction_count,
    COUNT(*) FILTER (WHERE transaction_type = 'income')::int     AS income_transaction_count
FROM transactions
WHERE tracking_period_id = $1 AND deleted_at IS NULL
`

type SummarizePeriodTotalsRow struct {
	TotalIncome             decimal.Decimal `json:"total_income"`
	TotalExpenses           decimal.Decimal `json:"total_expenses"`
	TotalTransfers          decimal.Decimal `json:"total_transfers"`
	TransactionCount        int32           `json:"transaction_count"`
	ExpenseTransactionCount int32           `json:"expense_transaction_count"`
	IncomeTransactionCount  int32           `json:"income_transaction_count"`
}

func (q *Queries) SummarizePeriodTotals(ctx context.Context, trackingPeriodID uuid.UUID) (SummarizePeriodTotalsRow, error) {
	row := q.db.QueryRow(ctx, summarizePeriodTotals, trackingPeriodID)
	var i SummarizePeriodTotalsRow
	err := row.Scan(
		&i.TotalIncome,
		&i.TotalExpenses,
		&i.TotalTransfers,
		&i.TransactionCount,
		&i.ExpenseTransactionCount,
		&i.IncomeTransactionCount,
	)
	return i, err
}

const summarizePeriodTotalsInRange = `-- name: SummarizePeriodTotalsInRange :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'income'), 0)::numeric  AS total_income,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'expense'), 0)::numeric AS total_expenses,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'transfer'), 0)::numeric AS total_transfers,
    COUNT(*)::int                                                AS transaction_count,
    COUNT(*) FILTER (WHERE transaction_type = 'expense')::int    AS expense_transaction_count,
    COUNT(*) FILTER (WHERE transaction_type = 'income')::int     AS income_transaction_count
FROM transactions
WHERE tracking_period_id = $1
  AND transaction_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
`

type SummarizePeriodTotalsInRangeParams struct {
	TrackingPeriodID uuid.UUID   `json:"tracking_period_id"`
	FromDate         pgtype.Date `json:"from_date"`
	ToDate           pgtype.Date `json:"to_date"`
}

type SummarizePeriodTotalsInRangeRow struct {
	TotalIncome             decimal.Decimal `json:"total_income"`
	TotalExpenses           decimal.Decimal `json:"total_expenses"`
	TotalTransfers          decimal.Decimal `json:"total_transfers"`
	TransactionCount        int32           `json:"transaction_count"`
	ExpenseTransactionCount int32           `json:"expense_transaction_count"`
	IncomeTransactionCount  int32           `json:"income_transaction_count"`
}

// Same aggregates as SummarizePeriodTotals but filtered to [from_date, to_date].
// Used to compute biweekly / weekly sub-period breakdowns on the fly.
func (q *Queries) SummarizePeriodTotalsInRange(ctx context.Context, arg SummarizePeriodTotalsInRangeParams) (SummarizePeriodTotalsInRangeRow, error) {
	row := q.db.QueryRow(ctx, summarizePeriodTotalsInRange, arg.TrackingPeriodID, arg.FromDate, arg.ToDate)
	var i SummarizePeriodTotalsInRangeRow
	err := row.Scan(
		&i.TotalIncome,
		&i.TotalExpenses,
		&i.TotalTransfers,
		&i.TransactionCount,
		&i.ExpenseTransactionCount,
		&i.IncomeTransactionCount,
	)
	return i, err
}
