// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTransactionByClientID = `-- name: GetTransactionByClientID :one
SELECT id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date FROM transactions
WHERE user_id = $1
  AND client_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetTransactionByClientIDParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ClientID *string   `json:"client_id"`
}

// Used by push to detect duplicates already committed by a previous push.
func (q *Queries) GetTransactionByClientID(ctx context.Context, arg GetTransactionByClientIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByClientID, arg.UserID, arg.ClientID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingPeriodID,
		&i.AccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.TransactionDate,
		&i.TransferAccountID,
		&i.AiCategorized,
		&i.AiConfidence,
		&i.AiSuggestedCategoryID,
		&i.VoiceInput,
		&i.RawVoiceText,
		&i.LocationLat,
		&i.LocationLng,
		&i.ClientID,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurringTransactionID,
		&i.OccurrenceDate,
	)
	return i, err
}

const syncPullAccounts = `-- name: SyncPullAccounts :many
SELECT id, user_id, name, account_type, currency, initial_balance, current_balance, icon, color, is_archived, display_order, created_at, updated_at, deleted_at FROM accounts
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullAccountsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

func (q *Queries) SyncPullAccounts(ctx context.Context, arg SyncPullAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, syncPullAccounts, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountType,
			&i.Currency,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.Icon,
			&i.Color,
			&i.IsArchived,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullBudgets = `-- name: SyncPullBudgets :many
SELECT id, user_id, tracking_period_id, category_id, amount, currency, alert_threshold_warning, alert_threshold_critical, notes, created_at, updated_at FROM budgets
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullBudgetsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

// Budgets have no deleted_at (hard delete). When a budget is deleted the row
// disappears; the client must request a full re-sync if it detects a gap.
// For now we return all budgets updated since $since.
func (q *Queries) SyncPullBudgets(ctx context.Context, arg SyncPullBudgetsParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, syncPullBudgets, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackingPeriodID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.AlertThresholdWarning,
			&i.AlertThresholdCritical,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullCategories = `-- name: SyncPullCategories :many
SELECT id, user_id, parent_id, name, category_type, icon, color, is_system, display_order, created_at, updated_at, deleted_at FROM categories
WHERE (user_id = $1 OR is_system = TRUE)
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullCategoriesParams struct {
	UserID   uuid.NullUUID      `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

// User-owned categories plus the shared system set. System categories are NOT
// embedded in the mobile app — the local DB (which the overlay bubble reads)
// only knows what sync delivers, so they must come down the wire too.
func (q *Queries) SyncPullCategories(ctx context.Context, arg SyncPullCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, syncPullCategories, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.CategoryType,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullGoalContributions = `-- name: SyncPullGoalContributions :many
SELECT id, savings_goal_id, user_id, tracking_period_id, transaction_id, amount, contribution_date, notes, created_at, updated_at FROM savings_goal_contributions
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullGoalContributionsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

func (q *Queries) SyncPullGoalContributions(ctx context.Context, arg SyncPullGoalContributionsParams) ([]SavingsGoalContribution, error) {
	rows, err := q.db.Query(ctx, syncPullGoalContributions, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoalContribution{}
	for rows.Next() {
		var i SavingsGoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.SavingsGoalID,
			&i.UserID,
			&i.TrackingPeriodID,
			&i.TransactionID,
			&i.Amount,
			&i.ContributionDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullRecurringTransactions = `-- name: SyncPullRecurringTransactions :many
SELECT id, user_id, account_id, category_id, name, transaction_type, amount, currency, description, frequency, custom_interval_days, day_of_month, day_of_week, start_date, end_date, last_generated_date, next_due_date, is_active, created_at, updated_at, deleted_at FROM recurring_transactions
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullRecurringTransactionsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

func (q *Queries) SyncPullRecurringTransactions(ctx context.Context, arg SyncPullRecurringTransactionsParams) ([]RecurringTransaction, error) {
	rows, err := q.db.Query(ctx, syncPullRecurringTransactions, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringTransaction{}
	for rows.Next() {
		var i RecurringTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Name,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Frequency,
			&i.CustomIntervalDays,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.StartDate,
			&i.EndDate,
			&i.LastGeneratedDate,
			&i.NextDueDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullSavingsGoals = `-- name: SyncPullSavingsGoals :many
SELECT id, user_id, name, description, icon, color, target_amount, current_amount, currency, start_date, target_date, status, linked_account_id, created_at, updated_at, achieved_at, deleted_at FROM savings_goals
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullSavingsGoalsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

func (q *Queries) SyncPullSavingsGoals(ctx context.Context, arg SyncPullSavingsGoalsParams) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, syncPullSavingsGoals, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Currency,
			&i.StartDate,
			&i.TargetDate,
			&i.Status,
			&i.LinkedAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AchievedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullTrackingPeriods = `-- name: SyncPullTrackingPeriods :many
SELECT id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition FROM tracking_periods
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullTrackingPeriodsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

func (q *Queries) SyncPullTrackingPeriods(ctx context.Context, arg SyncPullTrackingPeriodsParams) ([]TrackingPeriod, error) {
	rows, err := q.db.Query(ctx, syncPullTrackingPeriods, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingPeriod{}
	for rows.Next() {
		var i TrackingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.SequenceNumber,
			&i.ConfigStartDay,
			&i.ConfigDurationDays,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigPeriodMode,
			&i.IsTransition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPullTransactions = `-- name: SyncPullTransactions :many

SELECT id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date FROM transactions
WHERE user_id = $1
  AND updated_at > $2
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type SyncPullTransactionsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Since    pgtype.Timestamptz `json:"since"`
	PageSize int32              `json:"page_size"`
}

// Queries used exclusively by the sync-delta endpoints (GET /sync/pull, POST /sync/push).
// All pull queries share a common pattern:
//
//	WHERE user_id = $user AND updated_at > $since
//
// The caller passes a UTC timestamp; rows modified (created, updated, or
// soft-deleted) after that timestamp are returned so the client can apply
// the delta to its local Drift database.
// Includes soft-deleted rows (deleted_at IS NOT NULL) because the client must
// know about deletions to remove them from its local copy.
func (q *Queries) SyncPullTransactions(ctx context.Context, arg SyncPullTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, syncPullTransactions, arg.UserID, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackingPeriodID,
			&i.AccountID,
			&i.CategoryID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.TransactionDate,
			&i.TransferAccountID,
			&i.AiCategorized,
			&i.AiConfidence,
			&i.AiSuggestedCategoryID,
			&i.VoiceInput,
			&i.RawVoiceText,
			&i.LocationLat,
			&i.LocationLng,
			&i.ClientID,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecurringTransactionID,
			&i.OccurrenceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
