// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking_periods.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closePeriod = `-- name: ClosePeriod :one
UPDATE tracking_periods
SET status = 'closed', closed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition
`

func (q *Queries) ClosePeriod(ctx context.Context, id uuid.UUID) (TrackingPeriod, error) {
	row := q.db.QueryRow(ctx, closePeriod, id)
	var i TrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.SequenceNumber,
		&i.ConfigStartDay,
		&i.ConfigDurationDays,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigPeriodMode,
		&i.IsTransition,
	)
	return i, err
}

const createTrackingPeriod = `-- name: CreateTrackingPeriod :one
INSERT INTO tracking_periods (
    user_id,
    start_date,
    end_date,
    status,
    sequence_number,
    config_start_day,
    config_duration_days,
    config_period_mode,
    is_transition
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition
`

type CreateTrackingPeriodParams struct {
	UserID             uuid.UUID   `json:"user_id"`
	StartDate          pgtype.Date `json:"start_date"`
	EndDate            pgtype.Date `json:"end_date"`
	Status             string      `json:"status"`
	SequenceNumber     int32       `json:"sequence_number"`
	ConfigStartDay     int16       `json:"config_start_day"`
	ConfigDurationDays int16       `json:"config_duration_days"`
	ConfigPeriodMode   string      `json:"config_period_mode"`
	IsTransition       bool        `json:"is_transition"`
}

func (q *Queries) CreateTrackingPeriod(ctx context.Context, arg CreateTrackingPeriodParams) (TrackingPeriod, error) {
	row := q.db.QueryRow(ctx, createTrackingPeriod,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.SequenceNumber,
		arg.ConfigStartDay,
		arg.ConfigDurationDays,
		arg.ConfigPeriodMode,
		arg.IsTransition,
	)
	var i TrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.SequenceNumber,
		&i.ConfigStartDay,
		&i.ConfigDurationDays,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigPeriodMode,
		&i.IsTransition,
	)
	return i, err
}

const getActiveTrackingPeriod = `-- name: GetActiveTrackingPeriod :one
SELECT id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition FROM tracking_periods
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveTrackingPeriod(ctx context.Context, userID uuid.UUID) (TrackingPeriod, error) {
	row := q.db.QueryRow(ctx, getActiveTrackingPeriod, userID)
	var i TrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.SequenceNumber,
		&i.ConfigStartDay,
		&i.ConfigDurationDays,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigPeriodMode,
		&i.IsTransition,
	)
	return i, err
}

const getTrackingPeriodByID = `-- name: GetTrackingPeriodByID :one
SELECT id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition FROM tracking_periods
WHERE id = $1
`

func (q *Queries) GetTrackingPeriodByID(ctx context.Context, id uuid.UUID) (TrackingPeriod, error) {
	row := q.db.QueryRow(ctx, getTrackingPeriodByID, id)
	var i TrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.SequenceNumber,
		&i.ConfigStartDay,
		&i.ConfigDurationDays,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigPeriodMode,
		&i.IsTransition,
	)
	return i, err
}

const getTrackingPeriodForUser = `-- name: GetTrackingPeriodForUser :one
SELECT id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition FROM tracking_periods
WHERE id = $1 AND user_id = $2
`

type GetTrackingPeriodForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Like GetTrackingPeriodByID but scoped to the owner — safe to expose directly.
func (q *Queries) GetTrackingPeriodForUser(ctx context.Context, arg GetTrackingPeriodForUserParams) (TrackingPeriod, error) {
	row := q.db.QueryRow(ctx, getTrackingPeriodForUser, arg.ID, arg.UserID)
	var i TrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.SequenceNumber,
		&i.ConfigStartDay,
		&i.ConfigDurationDays,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigPeriodMode,
		&i.IsTransition,
	)
	return i, err
}

const listDueActivePeriods = `-- name: ListDueActivePeriods :many
SELECT id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition FROM tracking_periods
WHERE status = 'active' AND end_date < $1
ORDER BY user_id, sequence_number
`

// Active periods whose end_date is strictly before the given date (i.e. over).
func (q *Queries) ListDueActivePeriods(ctx context.Context, endDate pgtype.Date) ([]TrackingPeriod, error) {
	rows, err := q.db.Query(ctx, listDueActivePeriods, endDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingPeriod{}
	for rows.Next() {
		var i TrackingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.SequenceNumber,
			&i.ConfigStartDay,
			&i.ConfigDurationDays,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigPeriodMode,
			&i.IsTransition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingPeriodsByUser = `-- name: ListTrackingPeriodsByUser :many
SELECT id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition FROM tracking_periods
WHERE user_id = $1
ORDER BY sequence_number DESC
`

func (q *Queries) ListTrackingPeriodsByUser(ctx context.Context, userID uuid.UUID) ([]TrackingPeriod, error) {
	rows, err := q.db.Query(ctx, listTrackingPeriodsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingPeriod{}
	for rows.Next() {
		var i TrackingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.SequenceNumber,
			&i.ConfigStartDay,
			&i.ConfigDurationDays,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigPeriodMode,
			&i.IsTransition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reshapeTrackingPeriod = `-- name: ReshapeTrackingPeriod :one
UPDATE tracking_periods
SET end_date             = $1,
    config_period_mode   = $2,
    config_duration_days = $3,
    is_transition        = $4,
    updated_at           = NOW()
WHERE id = $5 AND status = 'active'
RETURNING id, user_id, start_date, end_date, status, sequence_number, config_start_day, config_duration_days, closed_at, created_at, updated_at, config_period_mode, is_transition
`

type ReshapeTrackingPeriodParams struct {
	EndDate            pgtype.Date `json:"end_date"`
	ConfigPeriodMode   string      `json:"config_period_mode"`
	ConfigDurationDays int16       `json:"config_duration_days"`
	IsTransition       bool        `json:"is_transition"`
	ID                 uuid.UUID   `json:"id"`
}

// Rewrites the end date and config metadata of an *active* period in place.
//
// This deliberately breaks domain rule 8 (configuration changes never reshape
// the active period), so it has exactly one caller: the onboarding carve-out in
// UserSettingsService.Update, which only fires for a pristine first period with
// no transactions. Do not reach for it anywhere else.
func (q *Queries) ReshapeTrackingPeriod(ctx context.Context, arg ReshapeTrackingPeriodParams) (TrackingPeriod, error) {
	row := q.db.QueryRow(ctx, reshapeTrackingPeriod,
		arg.EndDate,
		arg.ConfigPeriodMode,
		arg.ConfigDurationDays,
		arg.IsTransition,
		arg.ID,
	)
	var i TrackingPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.SequenceNumber,
		&i.ConfigStartDay,
		&i.ConfigDurationDays,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigPeriodMode,
		&i.IsTransition,
	)
	return i, err
}
