// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countTransactionsByAccount = `-- name: CountTransactionsByAccount :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (account_id = $2 OR transfer_account_id = $2)
`

type CountTransactionsByAccountParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AccountID uuid.UUID `json:"account_id"`
}

// Counts live movements touching an account, either as source or as the
// counter-account of a transfer. Used to decide whether its opening balance is
// still editable.
func (q *Queries) CountTransactionsByAccount(ctx context.Context, arg CountTransactionsByAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByAccount, arg.UserID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByPeriod = `-- name: CountTransactionsByPeriod :one
SELECT COUNT(*) FROM transactions
WHERE tracking_period_id = $1
  AND deleted_at IS NULL
`

// Counts live movements inside a tracking period. Used to decide whether the
// period is still pristine enough to be reshaped in place.
func (q *Queries) CountTransactionsByPeriod(ctx context.Context, trackingPeriodID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByPeriod, trackingPeriodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    tracking_period_id,
    account_id,
    category_id,
    transaction_type,
    amount,
    currency,
    description,
    notes,
    transaction_date,
    transfer_account_id,
    client_id,
    recurring_transaction_id,
    occurrence_date,
    ai_categorized,
    ai_confidence,
    ai_suggested_category_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date
`

type CreateTransactionParams struct {
	UserID                 uuid.UUID           `json:"user_id"`
	TrackingPeriodID       uuid.UUID           `json:"tracking_period_id"`
	AccountID              uuid.UUID           `json:"account_id"`
	CategoryID             uuid.NullUUID       `json:"category_id"`
	TransactionType        string              `json:"transaction_type"`
	Amount                 decimal.Decimal     `json:"amount"`
	Currency               string              `json:"currency"`
	Description            *string             `json:"description"`
	Notes                  *string             `json:"notes"`
	TransactionDate        pgtype.Date         `json:"transaction_date"`
	TransferAccountID      uuid.NullUUID       `json:"transfer_account_id"`
	ClientID               *string             `json:"client_id"`
	RecurringTransactionID uuid.NullUUID       `json:"recurring_transaction_id"`
	OccurrenceDate         pgtype.Date         `json:"occurrence_date"`
	AiCategorized          bool                `json:"ai_categorized"`
	AiConfidence           decimal.NullDecimal `json:"ai_confidence"`
	AiSuggestedCategoryID  uuid.NullUUID       `json:"ai_suggested_category_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.TrackingPeriodID,
		arg.AccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.TransactionDate,
		arg.TransferAccountID,
		arg.ClientID,
		arg.RecurringTransactionID,
		arg.OccurrenceDate,
		arg.AiCategorized,
		arg.AiConfidence,
		arg.AiSuggestedCategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingPeriodID,
		&i.AccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.TransactionDate,
		&i.TransferAccountID,
		&i.AiCategorized,
		&i.AiConfidence,
		&i.AiSuggestedCategoryID,
		&i.VoiceInput,
		&i.RawVoiceText,
		&i.LocationLat,
		&i.LocationLng,
		&i.ClientID,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurringTransactionID,
		&i.OccurrenceDate,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date FROM transactions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingPeriodID,
		&i.AccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.TransactionDate,
		&i.TransferAccountID,
		&i.AiCategorized,
		&i.AiConfidence,
		&i.AiSuggestedCategoryID,
		&i.VoiceInput,
		&i.RawVoiceText,
		&i.LocationLat,
		&i.LocationLng,
		&i.ClientID,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurringTransactionID,
		&i.OccurrenceDate,
	)
	return i, err
}

const listTransactionsByPeriod = `-- name: ListTransactionsByPeriod :many
SELECT id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date FROM transactions
WHERE user_id = $1 AND tracking_period_id = $2 AND deleted_at IS NULL
ORDER BY transaction_date DESC, created_at DESC
`

type ListTransactionsByPeriodParams struct {
	UserID           uuid.UUID `json:"user_id"`
	TrackingPeriodID uuid.UUID `json:"tracking_period_id"`
}

func (q *Queries) ListTransactionsByPeriod(ctx context.Context, arg ListTransactionsByPeriodParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByPeriod, arg.UserID, arg.TrackingPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackingPeriodID,
			&i.AccountID,
			&i.CategoryID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.TransactionDate,
			&i.TransferAccountID,
			&i.AiCategorized,
			&i.AiConfidence,
			&i.AiSuggestedCategoryID,
			&i.VoiceInput,
			&i.RawVoiceText,
			&i.LocationLat,
			&i.LocationLng,
			&i.ClientID,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecurringTransactionID,
			&i.OccurrenceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :one
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date
`

type SoftDeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingPeriodID,
		&i.AccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.TransactionDate,
		&i.TransferAccountID,
		&i.AiCategorized,
		&i.AiConfidence,
		&i.AiSuggestedCategoryID,
		&i.VoiceInput,
		&i.RawVoiceText,
		&i.LocationLat,
		&i.LocationLng,
		&i.ClientID,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurringTransactionID,
		&i.OccurrenceDate,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = $1,
    category_id = $2,
    transaction_type = $3,
    amount = $4,
    currency = $5,
    description = $6,
    notes = $7,
    transaction_date = $8,
    transfer_account_id = $9,
    updated_at = NOW()
WHERE id = $10 AND user_id = $11 AND deleted_at IS NULL
RETURNING id, user_id, tracking_period_id, account_id, category_id, transaction_type, amount, currency, description, notes, transaction_date, transfer_account_id, ai_categorized, ai_confidence, ai_suggested_category_id, voice_input, raw_voice_text, location_lat, location_lng, client_id, synced_at, created_at, updated_at, deleted_at, recurring_transaction_id, occurrence_date
`

type UpdateTransactionParams struct {
	AccountID         uuid.UUID       `json:"account_id"`
	CategoryID        uuid.NullUUID   `json:"category_id"`
	TransactionType   string          `json:"transaction_type"`
	Amount            decimal.Decimal `json:"amount"`
	Currency          string          `json:"currency"`
	Description       *string         `json:"description"`
	Notes             *string         `json:"notes"`
	TransactionDate   pgtype.Date     `json:"transaction_date"`
	TransferAccountID uuid.NullUUID   `json:"transfer_account_id"`
	ID                uuid.UUID       `json:"id"`
	UserID            uuid.UUID       `json:"user_id"`
}

// tracking_period_id is intentionally NOT updatable (a transaction stays in its
// period). The validate_transaction_period trigger re-checks date/period here.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.AccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.TransactionDate,
		arg.TransferAccountID,
		arg.ID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingPeriodID,
		&i.AccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.TransactionDate,
		&i.TransferAccountID,
		&i.AiCategorized,
		&i.AiConfidence,
		&i.AiSuggestedCategoryID,
		&i.VoiceInput,
		&i.RawVoiceText,
		&i.LocationLat,
		&i.LocationLng,
		&i.ClientID,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurringTransactionID,
		&i.OccurrenceDate,
	)
	return i, err
}
