// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_ai_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserAISettings = `-- name: DeleteUserAISettings :exec
DELETE FROM user_ai_settings
WHERE user_id = $1
`

func (q *Queries) DeleteUserAISettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAISettings, userID)
	return err
}

const getUserAISettings = `-- name: GetUserAISettings :one
SELECT id, user_id, provider, api_key_encrypted, base_url, model, enabled, created_at, updated_at FROM user_ai_settings
WHERE user_id = $1
`

func (q *Queries) GetUserAISettings(ctx context.Context, userID uuid.UUID) (UserAiSetting, error) {
	row := q.db.QueryRow(ctx, getUserAISettings, userID)
	var i UserAiSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.BaseUrl,
		&i.Model,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAISettings = `-- name: UpsertUserAISettings :one
INSERT INTO user_ai_settings (user_id, provider, api_key_encrypted, base_url, model, enabled)
VALUES ($1, $2, $3, $4, $5, TRUE)
ON CONFLICT (user_id) DO UPDATE SET
    provider          = EXCLUDED.provider,
    api_key_encrypted = EXCLUDED.api_key_encrypted,
    base_url          = EXCLUDED.base_url,
    model             = EXCLUDED.model,
    enabled           = TRUE
RETURNING id, user_id, provider, api_key_encrypted, base_url, model, enabled, created_at, updated_at
`

type UpsertUserAISettingsParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ApiKeyEncrypted []byte    `json:"api_key_encrypted"`
	BaseUrl         *string   `json:"base_url"`
	Model           *string   `json:"model"`
}

func (q *Queries) UpsertUserAISettings(ctx context.Context, arg UpsertUserAISettingsParams) (UserAiSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserAISettings,
		arg.UserID,
		arg.Provider,
		arg.ApiKeyEncrypted,
		arg.BaseUrl,
		arg.Model,
	)
	var i UserAiSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.BaseUrl,
		&i.Model,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
