// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (
    user_id,
    tracking_start_day,
    tracking_duration_days,
    default_currency,
    country_code,
    locale,
    theme,
    default_period_view,
    subscription_tier
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, tracking_start_day, tracking_duration_days, default_currency, country_code, locale, theme, default_period_view, subscription_tier, created_at, updated_at
`

type CreateUserSettingsParams struct {
	UserID               uuid.UUID `json:"user_id"`
	TrackingStartDay     int16     `json:"tracking_start_day"`
	TrackingDurationDays int16     `json:"tracking_duration_days"`
	DefaultCurrency      string    `json:"default_currency"`
	CountryCode          string    `json:"country_code"`
	Locale               string    `json:"locale"`
	Theme                string    `json:"theme"`
	DefaultPeriodView    string    `json:"default_period_view"`
	SubscriptionTier     string    `json:"subscription_tier"`
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, createUserSettings,
		arg.UserID,
		arg.TrackingStartDay,
		arg.TrackingDurationDays,
		arg.DefaultCurrency,
		arg.CountryCode,
		arg.Locale,
		arg.Theme,
		arg.DefaultPeriodView,
		arg.SubscriptionTier,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingStartDay,
		&i.TrackingDurationDays,
		&i.DefaultCurrency,
		&i.CountryCode,
		&i.Locale,
		&i.Theme,
		&i.DefaultPeriodView,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettingsByUserID = `-- name: GetUserSettingsByUserID :one
SELECT id, user_id, tracking_start_day, tracking_duration_days, default_currency, country_code, locale, theme, default_period_view, subscription_tier, created_at, updated_at FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettingsByUserID(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettingsByUserID, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingStartDay,
		&i.TrackingDurationDays,
		&i.DefaultCurrency,
		&i.CountryCode,
		&i.Locale,
		&i.Theme,
		&i.DefaultPeriodView,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
