// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (
    user_id,
    tracking_start_day,
    tracking_duration_days,
    default_currency,
    country_code,
    locale,
    theme,
    default_period_view,
    subscription_tier,
    tracking_period_mode
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, tracking_start_day, tracking_duration_days, default_currency, country_code, locale, theme, default_period_view, subscription_tier, created_at, updated_at, tracking_period_mode
`

type CreateUserSettingsParams struct {
	UserID               uuid.UUID `json:"user_id"`
	TrackingStartDay     int16     `json:"tracking_start_day"`
	TrackingDurationDays int16     `json:"tracking_duration_days"`
	DefaultCurrency      string    `json:"default_currency"`
	CountryCode          string    `json:"country_code"`
	Locale               string    `json:"locale"`
	Theme                string    `json:"theme"`
	DefaultPeriodView    string    `json:"default_period_view"`
	SubscriptionTier     string    `json:"subscription_tier"`
	TrackingPeriodMode   string    `json:"tracking_period_mode"`
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, createUserSettings,
		arg.UserID,
		arg.TrackingStartDay,
		arg.TrackingDurationDays,
		arg.DefaultCurrency,
		arg.CountryCode,
		arg.Locale,
		arg.Theme,
		arg.DefaultPeriodView,
		arg.SubscriptionTier,
		arg.TrackingPeriodMode,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingStartDay,
		&i.TrackingDurationDays,
		&i.DefaultCurrency,
		&i.CountryCode,
		&i.Locale,
		&i.Theme,
		&i.DefaultPeriodView,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackingPeriodMode,
	)
	return i, err
}

const getUserSettingsByUserID = `-- name: GetUserSettingsByUserID :one
SELECT id, user_id, tracking_start_day, tracking_duration_days, default_currency, country_code, locale, theme, default_period_view, subscription_tier, created_at, updated_at, tracking_period_mode FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettingsByUserID(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettingsByUserID, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingStartDay,
		&i.TrackingDurationDays,
		&i.DefaultCurrency,
		&i.CountryCode,
		&i.Locale,
		&i.Theme,
		&i.DefaultPeriodView,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackingPeriodMode,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET tracking_start_day     = COALESCE($1,     tracking_start_day),
    tracking_duration_days = COALESCE($2, tracking_duration_days),
    tracking_period_mode   = COALESCE($3,   tracking_period_mode),
    default_currency       = COALESCE($4,       default_currency),
    locale                 = COALESCE($5,                 locale),
    theme                  = COALESCE($6,                  theme),
    default_period_view    = COALESCE($7,    default_period_view)
WHERE user_id = $8
RETURNING id, user_id, tracking_start_day, tracking_duration_days, default_currency, country_code, locale, theme, default_period_view, subscription_tier, created_at, updated_at, tracking_period_mode
`

type UpdateUserSettingsParams struct {
	TrackingStartDay     *int16    `json:"tracking_start_day"`
	TrackingDurationDays *int16    `json:"tracking_duration_days"`
	TrackingPeriodMode   *string   `json:"tracking_period_mode"`
	DefaultCurrency      *string   `json:"default_currency"`
	Locale               *string   `json:"locale"`
	Theme                *string   `json:"theme"`
	DefaultPeriodView    *string   `json:"default_period_view"`
	UserID               uuid.UUID `json:"user_id"`
}

// Partial update: every field is nullable, and a NULL argument leaves the
// column untouched. updated_at is handled by the set_updated_at_user_settings
// trigger. country_code and subscription_tier are deliberately not editable
// here (the tier is server-controlled).
//
// Changing tracking_duration_days or tracking_period_mode does NOT touch the
// active tracking period: ClosePeriodTx re-reads these settings at close time,
// so the new configuration applies to the NEXT period. See
// UserSettingsService.Update for the single, narrow exception.
func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.TrackingStartDay,
		arg.TrackingDurationDays,
		arg.TrackingPeriodMode,
		arg.DefaultCurrency,
		arg.Locale,
		arg.Theme,
		arg.DefaultPeriodView,
		arg.UserID,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackingStartDay,
		&i.TrackingDurationDays,
		&i.DefaultCurrency,
		&i.CountryCode,
		&i.Locale,
		&i.Theme,
		&i.DefaultPeriodView,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackingPeriodMode,
	)
	return i, err
}
